GET http://localhost:3000/gameScores/

###

POST http://localhost:3000/gameScores/
Content-Type: application/json

{
    "username": "Ndeme",
    "playerTries": 2,
    "playerScore": 8
}

###

GET http://localhost:3000/rankRoutes/


###
POST http://localhost:3000/rankRoutes/
Content-Type: application/json

{
    "userID": "Ndeme",
    "userScores": {
        "score":9,
        "time": 2
    }
}