GET  http://localhost:3000/gameProgress


###
POST   http://localhost:3000/gameProgress
Content-Type: application/json

{
    "playerTries":3,
    "playerGameWin":false ,
    "playerBlocks": ["y","y","y","y","gtr"] 
}